// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taprtyccrycwyljtyihb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcHJ0eWNjcnljd3lsanR5aWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODA0MDUsImV4cCI6MjA3MzA1NjQwNX0._IG-s0fOBIeAT3r3Faw5Owd-GJchVs73d5k9h2lPYAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});